"""users table

Revision ID: 238b198b1478
Revises: 
Create Date: 2023-04-14 16:21:13.629377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238b198b1478'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands.txt auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands.txt ###


def downgrade():
    # ### commands.txt auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands.txt ###
